### ISSUE TITLE
ZOOM and PAN is not working with this source code. 

### ISSUE THREAD

**Issue by abdullegend** [fourctv/dicomViewerLib#2]
Zoom and PAN tool is not working if we clone and run by loading images. But in Demo it  is working fine. Kindly update what is missing in app source code?

**Comment by abdullegend** [comment]
Anyone can advise or resolve this issues please

**Comment by fourctv** [comment]
can you provide steps to reproduce the issue? both zoom and pan work fine in the demo app ([here](https://fourctv.github.io/dicomViewerDemo/)). It uses this library, so both tools do work as expected (and it does in my own app).

so if you can provide the steps to reproduce the issue you see on your side, I can try it here and look for a fix

**Comment by abdullegend** [comment]
Dear fourctv,
I have applied same steps given in gitup.  I have attached steps as shown in screenshot.
And additionally I have changed app module in source 
import  { DicomViewerModule} from 'dicomviewer'  
to 
import  { DicomViewerModule} from 'project/dicomviewer/src/lib/dicom-viewer' And also in app component.
When I click zoom tool and scroll mouse wheel it's getting events defined before function.
If my input data is not sufficient kindly advise I will try to give more datas as much I can.
please help in it, Thanks in advance.
![WhatsApp Image 2019-12-12 at 8 43 29 AM](https://user-images.githubusercontent.com/47899763/70731634-d9fe3880-1cbb-11ea-8b05-2cbb1e65ae02.jpeg)

**Comment by fourctv** [comment]
@abdullegend, why are you trying to use the library source in your project?

The instructions are for using the library as published on npmjs.org, not as source.

Now, what might be causing your troubles is the version of cornerstoneTools installed. That library has been massively updated recently and those changes might have broken my dicomviewerLib code.

Make sure you install a compatible version of that library:
`
npm install cornerstone-tools@2.5.0
`

Hope this fixes your issues.

(ps: I've updated ReadMe accordingly)

**Comment by abdullegend** [comment]
Dear Fourcetv,
We used cornerstone core 2.3.0
Cornerstone tools 2.5.0
WADO loader 2.0.0. The problem still persist. I have added screen shot of error herewith for your references.
![SAVE_20191218_194723](https://user-images.githubusercontent.com/47899763/71093537-6aaeaa00-21cf-11ea-92a3-38c3abaec3be.jpg)

**Comment by abdullegend** [comment]
Dear Fourcetv,
I tried as you advised and still it is not working.Please provide me the link and project as zipped file in order to run separately. Will helps me to close the issues and run the project successfully.

**Comment by abdullegend** [comment]
Dear Fourctv,
Thanks for your guidance and support.
The issues been fixed now.

**Comment by MuslumYilmaz** [comment]
cloned the repository and getting the same error. Pan and Zoom is not working. When I zoom i am getting the following error :  

 ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: 1.53'. Current value: 'null: 1.50'.

cornerstone-tools@2.5.0 has also installed but everything is still the same.

**Comment by martinmtwomm** [comment]
@MuslumYilmaz 

short answer: Delete the line ` if (this.currentImage) cornerstone.resize(this.element, true);` in the `ngAfterViewChecked()`- method inside the cornerstone.directive.spec.ts file. 

This should solve your problem (it worked for me)

I found an article after some research of what causes that specific error message (check out the link below at the end of the post). There was one interesting sentence which could explain why the published project doesn't throw this error:

> This error is only thrown in develop mode and for good reason; it is often a sign that you should refactor your code, as Angular warns you that this change in your expression will not be picked up when enabling production mode!

the link: https://medium.com/better-programming/expressionchangedafterithasbeencheckederror-in-angular-what-why-and-how-to-fix-it-c6bdc0b22787
